Repository arolla/nx-catalog, pull requests merged in 2023-05, with the labels that each got.

#4 Correction du pb de démarrage de l'app react
  package.json
  yarn.lock
Labels: bug, good first issue

#6 ci: 🐎update the github action version from v2 to v3
  .github/workflows/node.js.yml
Labels: ci

#10 Update node.js.yml
  .github/workflows/node.js.yml
Labels: ci

#9 mon projet avec le package.json
  nest-crud-kriss/package.json
  nest-crud-kriss/src/app.controller.spec.ts
  nest-crud-kriss/src/app.controller.ts
  nest-crud-kriss/src/app.module.ts
  nest-crud-kriss/src/app.service.ts
  nest-crud-kriss/src/app/app.controller.spec.ts
  nest-crud-kriss/src/app/app.module.ts
  nest-crud-kriss/src/app/app.service.spec.ts
  nest-crud-kriss/src/assets/.gitkeep
  nest-crud-kriss/src/connection/connection.controller.spec.ts
  nest-crud-kriss/src/connection/connection.controller.ts
  nest-crud-kriss/src/connection/connection.module.ts
  nest-crud-kriss/src/connection/connection.service.spec.ts
  nest-crud-kriss/src/connection/connection.service.ts
  nest-crud-kriss/src/dto/LoginDTO.ts
  nest-crud-kriss/src/dto/UserDTO.ts
  nest-crud-kriss/src/dto/todoDTO.ts
  nest-crud-kriss/src/entity/User.entity.ts
  nest-crud-kriss/src/entity/todo.entity.ts
  nest-crud-kriss/src/interface/Todos.interface.ts
  nest-crud-kriss/src/main.ts
  nest-crud-kriss/src/todos/todos.controller.spec.ts
  nest-crud-kriss/src/todos/todos.controller.ts
  nest-crud-kriss/src/todos/todos.module.ts
  nest-crud-kriss/src/todos/todos.service.spec.ts
  nest-crud-kriss/src/todos/todos.service.ts
  nest-crud-kriss/tsconfig.build.json
  nest-crud-kriss/tsconfig.json
Labels: enhancement

#8 feat: ✨created the React Header component
  react-book/.storybook/main.js
  react-book/src/components/header/Header.spec.tsx
  react-book/src/components/header/Header.stories.tsx
  react-book/src/components/header/Header.tsx
Labels: enhancement

#16 Update README.md
  README.md
Labels: documentation

#18 Update README.md
  README.md
Labels: documentation

#17 refactor: 🦄refactored a little bit the configuration for this project…
  .gitignore
  nest-crud-kriss/package.json
  nest-crud-kriss/project.json
  package.json
  react-book/src/components/header/Header.spec.tsx
  yarn.lock
Labels: refactoring
